spring:
  application:
    name: dubbo-consumer
server:
  port: ${random.int[20401,20409]}
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://localhost:2181