server:
  port: ${random.int[20401,20409]}
spring:
  application:
    name: dubbo-consumer
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.codetend.dubbo.consumer.utils.CommonDataDeserializer
      enable-auto-commit: false
    listener:
      ack-mode: manual
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://localhost:2181