server:
  port: 20501
spring:
  application:
    name: multi-source

master:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13307/sharding?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456

second:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13308/sharding?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456

logging:
  level:
    com.codetend.datasource.multi.mapper: debug
  file:
    name: D:\MyProjects\CloudLearning\logs\${spring.application.name}.log
