server:
  port: 20101
spring:
  application:
    name: service-provider
  cloud:
#    nacos:
#      discovery:
#        group: TEST_GROUP
#        server-addr: localhost:20000
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        produce1:
          destination: test-topic1
        produce2:
          destination: test-topic2
        produce3:
          destination: test-topic3

rocketmq:
  name-server: localhost:9876
  producer:
    group: native_topic_group1

elasticsearch:
  host: localhost
  port: 9200
  connTimeout: 3000
  socketTimeout: 5000
  connectionRequestTimeout: 500