server:
  port: 8761
  servlet:
    context-path: /cce
spring:
  application:
    name: Eureka-Discovery-Server
  security:
    user:
      name: eureka
      password: eureka
eureka:
  instance:
    hostname: localhost  # Eureka服务端实例名称
    prefer-ip-address: false
    instance-id: MAIN-EUREKA
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/