server:
  port: ${random.int[20102,20110]}
spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        group: TEST_GROUP
        server-addr: localhost:20000
    stream:
#      function:
#        #消费者端配置
#        definition: consumer
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        consumer1:
          destination: test-topic1
        consumer2:
          destination: test-topic2
        consumer3:
          destination: test-topic3
rocketmq:
  name-server: localhost:9876
