spring:
  application:
    name: dubbo-provider
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.codetend.dubbo.provider.utils.CommonDataSerializer
      bootstrap-servers: localhost:9092
      acks: 1
server:
  port: ${random.int[20301,20309]}
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.codetend.dubbo.provider.service
  protocol:
    port: ${random.int[20311,20319]}
